name: Docker Publish Starter

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build starter
      run: |
        docker build -t jsam07/node-ts-restful-api-starter:latest .

    - name: docker push
      run: |
        docker push jsam07/node-ts-restful-api-starter:latest
